apiVersion: apps/v1
kind: Deployment
metadata:
  name: "kubecertwatch"
  labels:
    app: "kubecertwatch"
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: {{ .Values.settings.metrics.port | quote }}
    prometheus.io/path: "/metrics"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "kubecertwatch"
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: {{ .Values.settings.metrics.port | quote }}
        prometheus.io/path: "/metrics"
      labels:
        app: "kubecertwatch"
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: kubecertwatch
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}            
          ports:
            - name: metrics
              containerPort: {{ .Values.settings.metrics.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: metrics
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: metrics
            initialDelaySeconds: 5
            periodSeconds: 10
          env:
            - name: DEBUG
              value: {{ .Values.settings.debug | quote }}
            - name: METRICS_PORT
              value: {{ .Values.settings.metrics.port | quote }}
            - name: CRON_SCHEDULE
              value: {{ .Values.settings.cronSchedule | quote }}
            - name: CLUSTER_NAME
              value: {{ required "A cluster name is required" .Values.settings.clusterName | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
