apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubecertwatch
  labels:
    app: kubecertwatch
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["cert-manager.io"]
  resources: ["certificates", "certificaterequests"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubecertwatch
  labels:
    app: kubecertwatch
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubecertwatch
subjects:
- kind: ServiceAccount
  name: kubecertwatch
  namespace: {{ .Release.Namespace }}
